# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "composer"
    directory: "/tools/deptrac"
    schedule:
      interval: "weekly"

  - package-ecosystem: "composer"
    directory: "/tools/infection"
    schedule:
      interval: "weekly"

  - package-ecosystem: "composer"
    directory: "/tools/jsonlint"
    schedule:
      interval: "weekly"

  - package-ecosystem: "composer"
    directory: "/tools/php-cs-fixer"
    schedule:
      interval: "weekly"

  - package-ecosystem: "composer"
    directory: "/tools/phpinsights"
    schedule:
      interval: "weekly"

  - package-ecosystem: "composer"
    directory: "/tools/phpmd"
    schedule:
      interval: "weekly"

  - package-ecosystem: "composer"
    directory: "/tools/phpstan"
    schedule:
      interval: "weekly"

  - package-ecosystem: "composer"
    directory: "/tools/psalm"
    schedule:
      interval: "weekly"
