framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false
    enabled_locales: ['en', 'fr']

    session:
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
        cookie_lifetime: 86400

    php_errors:
        log: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
