security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"
  
  providers:
    users:
        id: App\Security\UserProvider

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    web:
      lazy: true
      provider: users
      logout:
        path: app_connect_logout
      entry_point: App\Security\AuthenticationEntryPoint
      custom_authenticators:
        - App\Security\DiscordAuthenticator
        - App\Security\GoogleAuthenticator
        - App\Security\PassageAuthenticator

  access_control:
    - { path: ^/(en|fr)/album/dex$, roles: ROLE_TRAINER }
    - { path: ^/(en|fr)/album, roles: PUBLIC_ACCESS }
    - { path: ^/(en|fr)/connect, roles: PUBLIC_ACCESS }
    - { path: ^/(en|fr)/istration, roles: ROLE_ADMIN }
    - { path: ^/(en|fr)/trainer, roles: ROLE_TRAINER }
    - { path: ^/(en|fr)/election, roles: ROLE_TRAINER }
    - { path: ^/(en|fr)/outerroom, roles: ROLE_USER }
    - { path: ^/, roles: PUBLIC_ACCESS }

when@dev:
  security:            
    firewalls:
      web:
        custom_authenticators:
          - App\Security\FakeAuthenticator
