security:
    enable_authenticator_manager: true

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        user_provider:
            id: App\Security\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: user_provider
            logout:
                path: app_logout
            custom_authenticators:
                - App\Security\GoogleAuthenticator

    access_control:
        - { path: ^/(en|fr)/album/r/, roles: PUBLIC_ACCESS }
        - { path: ^/(en|fr)/connect/, roles: PUBLIC_ACCESS }
        - { path: ^/(en|fr)/istrateur/, roles: ROLE_ADMIN }
        - { path: ^/(en|fr)/trainer/, roles: ROLE_TRAINER }
        - { path: ^/(en|fr)/album/w/, roles: ROLE_TRAINER }
        - { path: ^/(en|fr)/outerroom/, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
