snc_redis:
    clients:
        session:
            type: phpredis
            alias: session
            dsn: "%env(REDISCLOUD_URL)%"

services:
    Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
        arguments:
            - '@snc_redis.session'
            - { 'ttl': 86400 }
