version: "3.4"

# Development environment override
services:
  php:
    build:
      target: app_php_dev
    volumes:
      - ./:/srv
      - ./docker/php/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
    environment:
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway

  caddy:
    volumes:
      - ./public:/srv/public:ro
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro

  test.moco:
    build:
      context: docker/moco/test
    volumes:
      - ./tests/resources/moco/:/var/moco:ro

  dev.moco:
    build:
      context: docker/moco/dev
    volumes:
      - ./tests/resources/moco/:/var/moco:ro
