version: "3.4"

services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    environment:
      - USER_ID=${USER_ID}
      - GROUP_ID=${GROUP_ID}
    expose:
      - 9000
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  apache:
    build:
      context: .
      dockerfile: ./docker/apache/Dockerfile
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    environment:
      - USER_ID=${USER_ID}
      - GROUP_ID=${GROUP_ID}
    ports:
      - 80:80
      - 443:443
    depends_on:
      - php
    volumes:
      - .:/var/www/html
      - ./docker/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./docker/apache/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
      - ./docker/apache/ssl:/usr/local/apache2/ssl/

  redis:
    image: redis:7.0-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --requirepass douze
    volumes:
      - redis:/data

  test.moco:
    build:
      context: docker/moco/test
    volumes:
      - ./tests/resources/moco/:/var/moco:ro

  dev.moco:
    build:
      context: docker/moco/dev
    volumes:
      - ./tests/resources/moco/:/var/moco:ro

volumes:
  redis:

networks:
  netapp:
    name: netapp

