name: Docker Compose Pull Up And Check
description: Use to docker compose pull and up then checks if services are correctly running
author: Renaud Douze
runs:
  using: "composite"
  steps:
    - name: Pull images
      shell: bash
      run: docker compose pull --ignore-pull-failures || true

    - name: Start services
      shell: bash
      run: docker compose up --build -d

    - name: Wait for services
      shell: bash
      run: |

        while status="$(docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" "$(docker compose ps -q php)")"; do
          case $status in
            starting) sleep 1;;
            healthy) exit 0;;
            unhealthy)
              docker compose ps
              docker compose logs
              exit 1
            ;;
          esac
        done
        exit 1

    - name: Check Moco logs
      run: docker compose logs moco_test

    - name: Check HTTP reachability
      shell: bash
      run: curl -v -o /dev/null http://localhost:8081

    - name: Check HTTPS reachability
      shell: bash
      run: curl  -vk -o /dev/null https://localhost:4431
