name: Docker Compose Pull Up And Check
description: Use to docker compose pull and up then checks if services are correctly running
author: Renaud Douze
runs:
  using: "composite"
  steps:
    - name: Pull images
      shell: bash
      run: docker compose pull --ignore-pull-failures || true

    - name: Start services
      shell: bash
      run: docker compose up --build --wait

    - name: Delete the cache
      shell: bash
      run: rm -Rf var/cache/*

    - name: Warmup the SF cache
      shell: bash
      run: docker compose exec -T php bin/console cache:clear --env=test