controllers:
    resource: ../src/Controller/
    exclude: '../src/Controller/{SecurityController}.php'
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: 'en|fr'
index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: app_home_index
        permanent: true
        
security:
    resource: '../src/Controller/SecurityController.php'
    type: attribute
    prefix: /
