services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      string $projectDir: "%kernel.project_dir%"
      string $backUrl: "%env(BACK_URL)%"
      string $backCafilePath: "%env(BACK_CAFILE_PATH)%"
      string $demoUserId: "%env(DEMO_USER_ID)%"
      string $resourcesVersionUrl: "%env(RESOURCES_VERSION_URL)%"

  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"
