parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $appApiUrl: '%env(APP_API_URL)%'
            string $projectDir: '%kernel.project_dir%'
            string $listAdmin: '%env(LIST_ADMIN)%'
            string $listTrainer: '%env(LIST_TRAINER)%'
            string $apiLogin: '%env(API_LOGIN)%'
            string $apiPassword: '%env(API_PASSWORD)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # <> Session
    Redis:
        class: Redis
        calls:
            - connect:
                - '%env(string:key:host:url:REDISCLOUD_URL)%'
                - '%env(int:key:port:url:REDISCLOUD_URL)%'
            - auth:
                - '%env(string:key:pass:url:REDISCLOUD_URL)%'

    Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
        arguments:
            - '@Redis'
    # </> Session
