services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $backUrl: '%env(BACK_URL)%'
            string $backCafilePath: '%env(BACK_CAFILE_PATH)%'
            int $electionTopCount: '%env(ELECTION_TOP_COUNT)%'
            int $electionCandidateCount: '%env(ELECTION_CANDIDATE_COUNT)%'
            
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

###> symfony/serializer ###
    Symfony\Component\PropertyInfo\Extractor\PhpDocExtractor: ~
    Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor: ~

    Symfony\Component\PropertyInfo\PropertyInfoExtractor:
        arguments:
            $listExtractors: [ '@Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor' ]
            $typeExtractors: [ '@Symfony\Component\PropertyInfo\Extractor\PhpDocExtractor', '@Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor' ]
            $descriptionExtractors: []
            $accessExtractors: []

    Symfony\Component\Serializer\Normalizer\ObjectNormalizer:
        arguments:
            $propertyTypeExtractor: '@Symfony\Component\PropertyInfo\PropertyInfoExtractor'
###< symfony/serializer ###
