name: CI

on:
  push:
    branches:
      - main
  pull_request: ~

jobs:
  quality:
    name: Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare
        uses: ./.github/actions/docker-compose
      - name: PHPCS
        run: make phpcs
      - name: PHPMD
        run: make phpmd
      - name: Psalm
        run: make psalm

  tests:
    needs: [quality]
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare
        uses: ./.github/actions/docker-compose
      - name: PHPStan
        run: make phpstan
      - name: PHPUnit
        run: make phpunit
