name: CI

on:
  push:
    branches:
      - main
  pull_request: ~

jobs:
  phpcs:
    name: Quality PHPCS
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        uses: ./.github/actions/docker-compose
      - name: Execution
        run: make phpcs

  phpmd:
    name: Quality PHPMD
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        uses: ./.github/actions/docker-compose
      - name: Execution
        run: make phpmd

  psalm:
    name: Quality Psalm
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        uses: ./.github/actions/docker-compose
      - name: Execution
        run: make psalm

  phpstan:
    needs: [phpcs, phpmd, psalm]
    name: Test PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        uses: ./.github/actions/docker-compose
      - name: Execution
        run: make phpstan

  phpunit:
    needs: [phpcs, phpmd, psalm]
    name: Test PHPUnit
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        uses: ./.github/actions/docker-compose
      - name: Execution
        run: make phpunit
