name: CI Tests

on:
  push:
    branches:
      - main
  pull_request: ~
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        description: "Docker Hub username"
        required: true
      DOCKERHUB_TOKEN:
        description: "Docker Hub token"
        required: true

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  PHP_CS_FIXER_IGNORE_ENV: 1

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Prepare
        uses: ./.github/actions/docker-compose
      - name: PHPUnit / Run
        run: |
          docker compose exec -T php php vendor/bin/phpunit tests/src/Unit --exclude-group="time-testing"

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Prepare
        uses: ./.github/actions/docker-compose
      - name: PHPUnit / Run
        run: |
          docker compose exec -T php php vendor/bin/phpunit tests/src/Integration --exclude-group="time-testing"

  browser-tests-chrome:
    name: Browser Tests (Chrome)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Prepare
        uses: ./.github/actions/docker-compose
      - name: PHPUnit / Run
        run: |
          docker compose exec \
            -e PANTHER_SELENIUM_HOST=http://chrome:4444/wd/hub \
            -e PANTHER_BROWSER_NAME=chrome \
            -T php php vendor/bin/phpunit tests/src/Browser --exclude-group="time-testing"

  browser-tests-firefox:
    name: Browser Tests (Firefox)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Prepare
        uses: ./.github/actions/docker-compose
      - name: PHPUnit / Run
        run: |
          docker compose exec \
            -e PANTHER_SELENIUM_HOST=http://firefox:4444/wd/hub \
            -e PANTHER_BROWSER_NAME=firefox \
            -T php php vendor/bin/phpunit tests/src/Browser --exclude-group="time-testing"

  measures:
    name: Measures (Coverage & Mutation Testing)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Prepare
        uses: ./.github/actions/docker-compose
      - name: Measures / Run Coverage
        run: |
          docker compose exec \
            -e XDEBUG_MODE=coverage \
            -T php php vendor/bin/phpunit \
            --exclude-testsuite="Browser Test Suite" \
            --coverage-clover=coverage.xml \
            --coverage-xml=build/coverage/coverage-xml \
            --log-junit=build/coverage/junit.xml
      - name: Measures / Composer install Infection
        shell: bash
        run: docker compose exec -T php composer install --working-dir=tools/infection --prefer-dist --no-progress --no-interaction
      - name: Measures / Run Infection
        run: |
          docker compose exec -T php php tools/infection/vendor/bin/infection \
            --threads=4 --no-progress \
            --skip-initial-tests --coverage=build/coverage \
            --min-msi=100 --min-covered-msi=100 \
            --filter=src

  security:
    name: Security
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Prepare
        uses: ./.github/actions/docker-compose
      - name: Security / Symfony Security Check
        run: |
          docker compose exec -T php symfony security:check
