name: Security

on:
  push:
    branches:
      - main
  pull_request: ~

jobs:
  composer-audit:
    name: Composer Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: composer audit
